"""Add user_id to Teacher

Revision ID: 18ed737db4a1
Revises: d0ed988fe8e7
Create Date: 2025-05-18 20:52:12.934151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ed737db4a1'
down_revision: Union[str, None] = 'd0ed988fe8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'teachers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_column('teachers', 'user_id')
    # ### end Alembic commands ###
