"""added father contact and mother contact together with removing parent column

Revision ID: 7da138ff7339
Revises: 
Create Date: 2025-06-09 15:06:15.109291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7da138ff7339'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('recipient_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('notifications', 'recipient_id')
    op.add_column('students', sa.Column('notification_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'notification_token')
    op.add_column('notifications', sa.Column('recipient_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column('notifications', 'recipient_token')
    # ### end Alembic commands ###
