name: Run Backend Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "sqlite:///./test.db"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write Firebase service account file
        run: |
          echo "${{ secrets.FIREBASE_CREDENTIALS_JSON }}" | base64 -d > firststep-school-firebase-adminsdk-fbsvc-538e257346.json

      - name: Run tests with pytest
        run: |
          pytest --cache-clear
